app:
  name: mini-online-shop
  port: ":4000"
  encryption:
    salt: 10
    jwt_secret: "secretbangetcuy"

db:
  host: "localhost"
  port: "5432"
  name: "online_shop"
  user: "macbookm1"
  password: "macbookm1"
  connection_pool:
    max_idle_connection: 10
    max_open_connection: 30
    max_lifetime_connection: 60
    max_idletime_connection: 60